Update environment.yaml
Scipy 1.9.1 was recently released on conda-forge:
https://anaconda.org/conda-forge/scipy/files
which causes creating a new environment in conda to use Scipy 1.9.1, which satisfies the original condition of scipy!=1.9.0.  With Scipy 1.9.1, this error can occur:

ImportError: cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats' (/projects/dram/anaconda3/envs/DRAM/lib/python3.10/sitepackages/scipy/stats/__init__.py)

Setting the version to be below (or equal to) scipy 1.8.1 should fix the issue!